version: '3'

services:
  # Set up as many of these as networks you want to collect keys for
  # This is an example of a ropsten node
    geth:
      image: ethereum/client-go
      volumes:
        - $HOME/.ethereum:/root/.ethereum
      command:
        --rpc --rpcaddr "0.0.0.0" --testnet

    api:
      build:
        context: ./api
        dockerfile: api.docker
        evironment:
          - ROCKSDB:/var/e2e # Location of the database
          - APIKEY:SecretKeyHere # A secret key to access the api
      ports:
        - "80:5000"

    # One of these per network also
    pkcollector:
       build:
          context: ./pubkey-collector
          dockerfile: pubkey-collector.docker
       environment:
         - CHAINID=3 ## This is ropsten specific
         - IPCADDR=/chaindata/geth.ipc
         - APIHOST:api
         - APIPORT:5000
         - APIKEY:SecretKeyHere # The same secret key used in the api
       volumes:
         - $HOME/.ethereum/testnet:/chaindata
       depends_on:
          - "geth"
          - "api"
