version: '3'

services:

    api:
      build:
        context: ./api
        dockerfile: Dockerfile-dev # Use the dev version without a proper webserver
      environment:
        - DB_HOST=api-db # Link to the postgres docker
        - DB_PORT=5432 
        - DB_NAME=e2e
        - DB_USER=e2e
        - DB_PASS=PutDBKeyHere
        - APIKEY=PutAPIKeyHere
      ports:
        - "80:5000" # expose the dev server

    api-db:
     image: postgres
     restart: always
     environment:
       - POSTGRES_PASSWORD=PutDBKeyHere
       - POSTGRES_USER=e2e
       - POSTGRES_DB=e2e 
     volumes:
       - ./api-db/:/docker-entrypoint-initdb.d
       - ./api-database:/var/lib/postgresql/data
     ports:
       - "5432:5432"

  # Set up as many of these as networks you want to collect keys for
  # This is an example of a ropsten node
    geth:
      image: ethereum/client-go
      volumes:
        - $HOME/.ethereum:/root/.ethereum
      command:
        --rpc --rpcaddr "0.0.0.0" --testnet

    pkcollector-ropsten:
       build:
          context: ./pubkey-collector
       environment:
         - CHAINID=3 ## This is ropsten specific
         - IPCADDR=/chaindata/geth.ipc
         - APIHOST=api
         - APIPORT=5000
         - APIKEY=PutAPIKeyHere # The same secret key used in the api
       volumes:
         - $HOME/.ethereum/testnet:/chaindata
       depends_on:
         - "geth"
         - "api"

